### ISSUE TITLE
Organizational matters - don't hesitate to ask a question by replying to this issue!

### ISSUE THREAD

**Issue by simonsimson** [FUB-HCC/seminar_critical-social-media-analysis#1]

**Comment by Rahaf66** [comment]
Where can I find the slides of the last lecture?
Thanks

**Comment by simonsimson** [comment]
I just uploaded the slides here:
https://github.com/FUB-HCC/seminar_critical-social-media-analysis/tree/master/Slides_sessions
Best, SH

**Comment by Rahaf66** [comment]
Thank you very much
Bests
