### ISSUE TITLE
YTDT video list module / [proposed label] tech

### ISSUE THREAD

**Issue by SabinaP17** [FUB-HCC/seminar_critical-social-media-analysis#10]
I'm having trouble extracting the data from my Youtube video using the YTDT
video list module.

**Problem description:** 
If I introduce the video URL in the "Search query" section, I get in the
.tab-file a list of videos that have a similar URL with the one I've
searched for. However, no comment list is available, only the total number
of comments per video.
If I introduce the video URL in the "Manual selection", I don't get any
information about the video or comments in the .tab-file. The file is
empty.
Could you please explain again how to extract the comments from a video
using the YTDT video list module?

**Comment by simonsimson** [comment]
1. Entering the URL into the search query field will not work. You have to use the video id, which is part of the URL. 
You can also use the following tool to extract it: https://commentpicker.com/youtube-video-id.php

2. To extract comments, you need the 'video info' module, not the 'video list' module.
https://tools.digitalmethods.net/netvizz/youtube/mod_video_info.php

Best, SH

**Comment by SabinaP17** [comment]
Thank you very much for the information.
