### ISSUE TITLE
“On the Dangers of Stochastic Parrots: Can Language Models Be Too Big?”

### ISSUE THREAD

**Issue by isaschm** [FUB-HCC/seminar_critical-social-media-analysis#38]
I would recommend this article, not necessarily just because it sheds light on why Timnit Gebru was fired from Google, but because the paper Gebru and her colleagues were working on is very much related to the technologies and concepts we use in this course.

https://www.technologyreview.com/2020/12/04/1013294/google-ai-ethics-research-paper-forced-out-timnit-gebru/

**Comment by simonsimson** [comment]
This is great input, thank you Isabel!
